spring:
  datasource:
    ##########################  druid配置   ##########################
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/black-fire?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: root123
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: smartpark
        login-password: 123456
  cloud:
    nacos:
      discovery:
        # 注册地址
        server-addr: localhost:8848
        register-enabled: true
        #命名空间 不同命名空间之间不能调用，用于环境隔离
        namespace: 6519ee42-b431-4fb7-a71e-17b45ab7bc1a
        # 分组，不同分组之间不能调用，用于微服务之间的隔离
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redispass
      database: 9
      timeout: 5000
  ai:
    openai:
      base-url: https://api.openai.com/
      api-key: hweuiofjqwopfjerjfewdc
      chat:
        option:
          model: gpt-4.0-turbo
          temperature: 0.7F
          max-tokens: 200
mybatis:
  type-aliases-package: com.blackfire.aicloud.provider.dao.entity
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

#放行url
ignore:
  urls:
    - /test
ai:
  ali-tongyi:
    api-key: sk-170754a2f178474d9d2a223b63c88715
    model: qwen-turbo
    stream: false
  openai:
    base-url: https://api.openai.com/
    api-key: hweuiofjqwopfjerjfewdc
    chat:
      option:
        model: gpt-4.0-turbo
  xunfei:
    base-url: https://spark-api-open.xf-yun.com
    api-key: vqWkutlnzljSflBuivZK:TvhUlglKolYeKoMxskYq
    chat:
      option:
        model: generalv3.5
#        model: generalv3
  baidu:
    api-key: 1ZRbMiGWaO2yFKFoLcxRMO4M
    secret: 4fd1UDVuExWBpAgNnH1iuHZzO6JaZz48