spring:
  datasource:
    ##########################  druid配置   ##########################
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.73:13306/chengyu_037?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: kh0062
    password: on+cOQm=3m7uTf8w
  cloud:
    nacos:
      discovery:
        # 注册地址
        server-addr: 127.0.0.1:8848
        register-enabled: true
        #命名空间 不同命名空间之间不能调用，用于环境隔离
        #namespace: sada-asas-dasa-dasas
        # 分组，不同分组之间不能调用，用于微服务之间的隔离
        group: DEFAULT_GROUP
  data:
    redis:
      host: 192.168.0.73
      port: 16379
      password: 4Jd7eP6JBJjy
      database: 9
      timeout: 5000
  ai:
    openai:
      base-url: https://api.openai.com/
      api-key: hweuiofjqwopfjerjfewdc
      chat:
        option:
          model: gpt-4.0-turbo
          temperature: 0.7F
          max-tokens: 200
mybatis:
  type-aliases-package: com.blackfire.aicloud.provider.dao.entity
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

#放行url
ignore:
  urls:
    - /test
ai:
  ali-tongyi:
    api-key: sk-170754a2f178474d9d2a223b63c88715
    model: qwen-turbo
    stream: false
  openai:
    base-url: https://api.openai.com/
    api-key: hweuiofjqwopfjerjfewdc
    chat:
      option:
        model: gpt-4.0-turbo
  xunfei:
    base-url: https://spark-api-open.xf-yun.com
    api-key: vqWkutlnzljSflBuivZK:TvhUlglKolYeKoMxskYq
    chat:
      option:
        model: generalv3.5
#        model: generalv3
  baidu:
    api-key: 1ZRbMiGWaO2yFKFoLcxRMO4M
    secret: 4fd1UDVuExWBpAgNnH1iuHZzO6JaZz48