server:
  port: 8090
  servlet:
    context-path: /blackfire
spring:
  application:
    name: blackfire-aicloud
  profiles:
    active: local
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 100MB

